# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
# security:

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:         [ROLE_QUOTE_EDIT, ROLE_CUSTOMER_EDIT]
        ROLE_QUOTE_EDIT:    ROLE_USER
        ROLE_CUSTOMER_EDIT: ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/[^/]+/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[^/]+/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[^/]+/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/customers/?$, role: ROLE_USER }
        - { path: ^/[^/]+/quotes.*, role: ROLE_QUOTE_EDIT }
        - { path: ^/[^/]+/customers.*, role: ROLE_CUSTOMER_EDIT }
