# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.db:
        class: AppBundle\Lib\Db
        arguments: ['@doctrine.orm.entity_manager']
    app.logic:
        class: AppBundle\Lib\Logic
        arguments: ['@app.db']
