version: "3.9"

volumes:
  dbdata:

services:
  db:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/mysql
  web:
    depends_on:
      - db
    image: apache-php-7.3
    build: ./images/apache-php-7.3
    ports:
      - 8888:80
    command: bash -c "apache2ctl -D FOREGROUND"
    volumes:
      - type: bind
        source: ./../../
        target: /opt/quotes
      - type: bind
        source: ./sites-enabled
        target: /etc/apache2/sites-enabled
